### ISSUE TITLE
Daily "To-Do"s

### ISSUE THREAD

**Issue by mk4111** [ayooo-team/prototype#10]
### 24/03/2016

Aims:
- [x] Set up testing environment
- [x] Set up structure of MVP 
- [x] Set up React-Router
- [x] Set up Hapi-Server
- [x] Sign up page: OAuth (Firebase), User Details Database (Firebase)

Stretch: 
- [ ] Write Tests

Remember:
- [x] Meeting at 14:00 with Client

**Comment by iteles** [comment]
:heart:

**Comment by mk4111** [comment]
### Easter Weekend

Look into:
- [x] ElasticSearch --> .csv ---> google spreadsheet?

**Comment by mk4111** [comment]
### 01/04/2016
- [ ] Reset button tag browser default settings.
- [x] Export proto.io wireframes.
- [x] Heroku link up
- [x] Heroku SearchBox addon
- [ ] CSS
- [x] Add catch for new users to have to type in their email addresses again (to sign up)

**Comment by mk4111** [comment]
### 04/04/2016
- [x] CSS
- [ ] add ajax requests
- [x] on clicking confirmation button, check if user details are stored
- [ ] ~~make sure that input values can't get script injected~~
- [x] make sure that input values can only be of a certain type (e.g. numbers)

#### !!!!
- [x] make parcelDetails - content description page
- [x] make page to set delivery date
- [x] Redirect to dashboard when user has finished #48 
- [ ] Make sure login page does **not** appear when user is authenticated #35 
- [ ] Look at date/time pickers #49 
- [ ] Non-alert alerts #50
- [ ] Download CSVs #51
- [x] Work out how to make whole div clickable #52
- [x] Sort out inputs #53
